### ISSUE TITLE
read elements string as case insensitive

### ISSUE THREAD

**Issue by jrmlhermitte** [XraySpectroscopy/XrayDB#11]
It would be nice that XrayDB.atomic_number be case insensitive. Would this be a reasonable add?

For ex:

``` python
import xraydb
_XrayDB = xraydb.XrayDB()
Z = _XrayDB.atomic_number('Ag')
```

works, but 

``` python
Z = _XrayDB.atomic_number('ag')
```

does not.

There may be drawbacks which I may have missed. If the community is okay for the change I can submit a PR (if it saves time). 

thanks!

(PS: please correct me if my usage is not the intended one)

**Comment by newville** [comment]
@ordirules  I don not have a very strong preference, but case sensitivity for atomic symbols is pretty common.   Should "co" be interpreted as "cobalt" or "carbon oxygen"?  When only one element is possible, case sensitivity is not necessary, but when more than one element is possible, case sensitivity is necessary.
So, I'm ever so slightly against allowing case insensitivity sometimes but not always.   But, I could be persuaded.

**Comment by jrmlhermitte** [comment]
that's a good point. I lean more towards your side (switched from xraylib which was case insensitive)
